### ISSUE TITLE
El joc no acaba

### ISSUE THREAD

**Issue by ghost** [Ivaanfg/PROJECTE-PYTHON#2]
![image](https://user-images.githubusercontent.com/98090116/157230892-043a6294-ff94-4fb7-bfd6-05818fbcbccc.png)

Quan un jugador arriba el joc hauria d'acabar. El que passa és que segeuix i llavors el programa falla.

**Comment by Ivaanfg** [comment]
D'acord avui ho acabarem de mirar

**Comment by ghost** [comment]
Crec que això es pot tancar
